import pandas as pd
import numpy as np
from scipy import stats
import os

## load_rivers section

flow_path = os.getenv("FLOW_DATA_PATH", "../../data/Downstream_Estimate_All_Rivers_rolling60.csv")
chemistry_path = "../../data/wq_uncen_all.xlsx"
out_data_path = os.getenv("WRTDS_DATA_ROOT", "../../autogenerated_results/workspace_scaled")
areas_path = "../../data/watershed_area_stats.csv"

#### Adapted from data_prep, itself adapted from load_rivers

rivers = ["Aysen", "Puelo", "Palena", "Cisnes", "Yelcho"]
# Enter in basin area here
#areas = {"Aysen": 12214.02943, "Puelo": 8926.765273, "Palena": 13142.85061, "Cisnes": 5093.113614, "Yelcho": 11366.91242} # km^2
areas = pd.read_csv(areas_path).set_index("river_name")["total_area"].to_dict()
areas_l = [areas[r] for r in rivers]

with pd.ExcelFile(chemistry_path) as DATA:
    Aysen_Chem_raw  = pd.read_excel(DATA, 'Aysen',  skiprows=range(2), comment="#")
    Puelo_Chem_raw  = pd.read_excel(DATA, 'Puelo',  skiprows=range(2), comment="#")
    Cisnes_Chem_raw = pd.read_excel(DATA, 'Cisnes', skiprows=range(2), comment="#")
    Yelcho_Chem_raw = pd.read_excel(DATA, 'Yelcho', skiprows=range(2), comment="#")
    Palena_Chem_raw = pd.read_excel(DATA, 'Palena', skiprows=range(2), comment="#")
    detection_limits = pd.read_excel(DATA, 'detection_limits', index_col="Chem")["Limit"]

raw_chem_dfs = {
    "Aysen": Aysen_Chem_raw,
    "Puelo": Puelo_Chem_raw,
    "Cisnes": Cisnes_Chem_raw,
    "Yelcho": Yelcho_Chem_raw,
    "Palena": Palena_Chem_raw
}

chem_dfs = dict()
for riv, df in raw_chem_dfs.items():
    df.name = riv
    df.set_index("Date", inplace=True)
    
    newdf = df.drop(columns=["Team", "Site", "replicate"], errors="ignore")
    newdf = newdf.loc[:, newdf.dtypes != "object"].groupby("Date").mean()
    chem_dfs[riv] = newdf

assert all([df.index.is_unique for df in chem_dfs.values()]) # check for duplicate dates


## Flow df section

all_flow_df = pd.read_csv(flow_path).set_index("Date")
all_flow_df.index = pd.to_datetime(all_flow_df.index) # Index should be date even though it's converted back later, best for trimming

daily_flow_dfs = {col: all_flow_df[col].rename("Q").to_frame() for col in all_flow_df}

start_date = pd.to_datetime("2022-02-25")
end_date = pd.to_datetime("2023-12-31")

print(f"Trimming data to the period from {start_date} to {end_date}")

for r, dailydf in daily_flow_dfs.items():
    dailydf = dailydf.sort_values("Date")
    dailydf = dailydf.loc[start_date:end_date]
    print(f"River {r} data range after trimming: {dailydf.index.min()} to {dailydf.index.max()}")
    daily_flow_dfs[r] = dailydf
    

## Chemistry preop section
##### This is where you decide which constituents to analyze

chemicals = ["TN", "TP", "Fe", "DOC", "dSi", "TSS"]


######Insert data post prep segment

# identify start and end dates
rng_dfs = dict()
for name, df in chem_dfs.items():

    # print date range
    rng_df = pd.DataFrame(
        data=[
            [df[c].dropna().index[0] for c in chemicals],
            [df[c].dropna().index[-1] for c in chemicals],
        ],
        columns=chemicals,
        index=["start", "end"]
    )

    rng_df["inner"] = [rng_df.loc["start"].max(), rng_df.loc["end"].min()]
    rng_df["outer"] = [rng_df.loc["start"].min(), rng_df.loc["end"].max()]
    assert rng_df.at["start", "inner"] < rng_df.at["end", "inner"] # in case there is no overlap between some of the dates of the chem samples
    assert rng_df.at["start", "outer"] < rng_df.at["end", "outer"] # should be logically unnecessary but whatever
    print(name)
    display(rng_df)

    rng_dfs[name] = rng_df

    # save rng_df -- to be used by a post processing script
    rng_big_df = pd.concat(rng_dfs)
    rng_big_df.index.set_names(["river", "which"], inplace=True)
    rng_big_df.to_csv("../../autogenerated_results/chem sample ranges.csv")

#####End data post prep segment

## Create the R dataframes section

outliers_removed = []


Daily_dict = dict()
Sample_dict = dict()
Info_dict = dict()
for r in rivers:
  Daily_dict[r] = daily_flow_dfs[r].reset_index() # I think reformatting index helps with rpy2
  Daily_dict[r]["Date"] = Daily_dict[r]["Date"].dt.strftime("%Y-%m-%d") # I think reformatting index helps with rpy2

  for c in chemicals:
      Info_dict[(r,c)] = pd.DataFrame(
                index=["param.units", "shortName",  "paramShortName", "constitAbbrev",
                         "drainSqKm",   "station.nm", "param.nm",       "staAbbrev"   ],
                data=   ["mg/l",         r,            c,                c,
                          areas[r],      r,            c,                r            ]
            ).transpose()
      wdf = chem_dfs[r][c].to_frame().copy()
      wdf["remarks"] = np.where((wdf[c] == "b.d."), "<", "NA") # for b.d. in remarks
      print("Amt b.d.: ", len(wdf[wdf["remarks"] == "<"]))
      wdf[c] = wdf[c].replace("b.d.", detection_limits[c]) # replce b.d. with the detection limits
      wdf[c] = wdf[c].replace([0, "", None, np.nan], "NA")
      print("Amt NA: ", len(wdf[wdf[c] == "NA"]))
      wdf = wdf[wdf[c] != "NA"]  # Remove rows with "NA" in the chemical concentration column

      mean, std = wdf[c].mean(), wdf[c].std()

    ###### NOTE: THIS IS WHERE OUTLIER THRESHOLDS ARE SET IN TERMS OF STANDARD DEVIATION.
    ###### TO AVOID REMOVING ANY OUTLIERS, SET THE LIMITS TO A HIGH NUMBER TIMES THE STANDARD DEVIATION
    ###### THIS WAS PREVIOUSLY SET TO 3*SD, BUT UPDATED TO 10*SD ON APRIL 10, 2025

      lim1 = mean - 10*std
      lim2 = mean + 10*std

      # Identify and log outliers before removing them
      outliers = wdf[(wdf[c] > lim2) | (wdf[c] < lim1)]
      for index, row in outliers.iterrows():
          outliers_removed.append({
              "River": r,
              "Constituent": c,
              "Date": index,
              "Value": row[c],
              "Standard Deviations from Mean": (row[c] - mean) / std
          })

      # Print the number of outliers found for debugging
      print(f"Outliers found for {r} - {c}: {len(outliers)}")

      # Remove outliers
      wdf = wdf[(wdf[c] > lim1) & (wdf[c] < lim2)]

      # Divide values by 1000 to convert from ug/L to mg/L
      wdf[c] /= 1000

    #new TEMPORARY insert 2/5/2025 to trim conc data to available streamflow data date range
      flow_dates = daily_flow_dfs[r].index  # Get available flow dates
      wdf = wdf[wdf.index.isin(flow_dates)]  # Keep only concentration data for dates with flow
    #end insert
    
      # Because of rpy2 bugs or something idk, we need to convert the datetime to string first
      wdf["Date"] = wdf.index.strftime("%Y-%m-%d")
      Sample_dict[(r,c)] = wdf[["Date", "remarks", c]]

# Save outliers to CSV
outliers_df = pd.DataFrame(outliers_removed)
outliers_df.to_csv(out_data_path+"outliers_removed.csv", index=False)

# Verify the length of the trimmed streamflow data
for r, dailydf in daily_flow_dfs.items():
    num_days = (dailydf.index.max() - dailydf.index.min()).days + 1  # Add 1 to include both start and end dates
    print(f"River {r} has {num_days} days of data in the trimmed period.")

# Also verify if the number of leap years in the period
num_leap_years = len([year for year in range(start_date.year, end_date.year + 1) if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)])
print(f"Number of leap years in the period: {num_leap_years}")

# Check for any blank entries or NaNs in the flow files
for r, dailydf in daily_flow_dfs.items():
    if dailydf.isnull().values.any():
        print(f"Warning: River {r} has blank entries or NaNs in the flow data.")
    else:
        print(f"River {r} has no blank entries or NaNs in the flow data.")
