import pandas as pd
import numpy as np
from scipy import stats
import os

rivers = ["Puelo", "Yelcho", "Palena", "Cisnes", "Aysen"]
chemicals = ["TN", "TP", "Fe", "dSi", "TSS"]

default_flow_path = os.getenv("FLOW_DATA_PATH", "../../data/Downstream_Estimate_All_Rivers_rolling60.csv")
default_chemistry_path = "../../data/wq_uncen_all.xlsx"
default_out_data_path = os.getenv("WRTDS_DATA_ROOT", "../../autogenerated_results/workspace_scaled")
default_areas_path = "../../data/watershed_area_stats.csv"

areas = None # Need to load areas in the main module

start_date = "2022-02-25"
end_date = "2023-12-31"

def load_areas(path=default_flow_path):
    return pd.read_csv(path).set_index("river_name")["total_area"].to_dict()

def load_chem_dfs(path=default_chemistry_path):
    with pd.ExcelFile(path) as DATA:
        chem_dfs = {
            riv: pd.read_excel(
                    DATA,
                    riv,
                    skiprows=range(2),
                    comment="#"
                )
            for riv in rivers
        }
        detection_limits = pd.read_excel(DATA, "detection_limits", index_col="Chem")["Limit"]
    # Need to get rid of replicates
    for chem, df in chem_dfs.items():
        df.set_index(pd.to_datetime(df["Date"]).rename("date_idx"), inplace=True)
        df["Date"] = df["Date"].astype("str")
        df.drop(columns=["Team", "Site", "replicate"], errors="ignore", inplace=True)

        # Mean same dates (replicates together... dropping the "object" columns too... could cause b.d. to be dropped? FIXME
        #chem_dfs[chem] = df.loc[:, df.dtypes != "str"].groupby("Date").mean()
        chem_dfs[chem] = df
        
        # If we can modify the process a bit... maybe replace b.d. values with -0
    
    rng_df = pd.DataFrame(
        columns=chemicals,
        index=pd.MultiIndex.from_product([rivers, ["start", "end"]], names=("river", "which"))
    )
    inner_outer = pd.DataFrame(
        columns=["inner", "outer"],
        index=pd.MultiIndex.from_product([rivers, ["start", "end"]], names=("river", "which"))
    )
    for riv in rivers:
        for chem in chemicals:
            idx = chem_dfs[riv][chem].dropna().index
            rng_df.loc[(riv, "start"), chem] = idx[0]
            rng_df.loc[(riv, "end"), chem] = idx[-1]
        
        inner_outer.loc[(riv, "start"), "inner"] = rng_df.loc[(riv, "start")].min()
        inner_outer.loc[(riv, "end"), "inner"] = rng_df.loc[(riv, "end")].max()
        inner_outer.loc[(riv, "start"), "outer"] = rng_df.loc[(riv, "start")].max()
        inner_outer.loc[(riv, "end"), "outer"] = rng_df.loc[(riv, "end")].min()

        assert inner_outer.at[(riv, "start"), "inner"] < inner_outer.at[(riv, "end"), "inner"] 
        # in case there is no overlap between some of the dates of the chem samples
        assert inner_outer.at[(riv, "start"), "outer"] < inner_outer.at[(riv, "end"), "outer"]
        # should be logically unnecessary but whatever
    
    rng_df = pd.concat([rng_df, inner_outer], axis=1)
    
    return chem_dfs, detection_limits, rng_df



# IMPORTANT: The original data_prep mde a dict of flow dfs, but I think that since
# it all comes from one big flow file, there is no point in that
def load_flow_df(path=default_flow_path, start_date=start_date, end_date=end_date):
    all_flow_df = pd.read_csv(path)
    
    # Trim to date
    all_flow_df.set_index("Date", inplace=True)
    all_flow_df = all_flow_df.loc[start_date:end_date]
    
    return all_flow_df


# This is for keeping a log of all the outliers removed
outliers_removed = []

def format_infodf(riv, chem, areas=areas):
    return pd.DataFrame(
                index=["param.units", "shortName",  "paramShortName", "constitAbbrev",
                         "drainSqKm",   "station.nm", "param.nm",       "staAbbrev"   ],
                data=   ["mg/l",         riv,            chem,                chem,
                          areas[riv],    riv,            chem,                riv           ]
                ).transpose()

# Generate a chemistry and info dataframe to be passed to the R process
# Note: outliers_removed is a mutable list to keep a log of all the outliers removed
def format_wdf(riv, chem,
               flow_df, chem_dfs, detection_limits,
               areas=areas, outliers_removed=outliers_removed):
    
    wdf = chem_dfs[riv][["Date", chem]]
    wdf["remarks"] = np.where((wdf[chem] == "b.d."), "<", "NA") # for b.d. in remarks
    print("Amt b.d.: ", (wdf["remarks"] == "<").sum())
    wdf[chem] = wdf[chem].replace("b.d.", detection_limits[chem]) # replce b.d. with the detection limits
    wdf[chem] = wdf[chem].replace([0, "", None, np.nan], "NA")
    print("Amt NA: ", (wdf[chem] == "NA").sum())
    wdf = wdf[wdf[chem] != "NA"]  # Remove rows with "NA" in the chemical concentration column
    
    mean, std = wdf[chem].mean(), wdf[chem].std()
    
    ###### NOTE: THIS IS WHERE OUTLIER THRESHOLDS ARE SET IN TERMS OF STANDARD DEVIATION.
    ###### TO AVOID REMOVING ANY OUTLIERS, SET THE LIMITS TO A HIGH NUMBER TIMES THE STANDARD DEVIATION
    ###### THIS WAS PREVIOUSLY SET TO 3*SD, BUT UPDATED TO 10*SD ON APRIL 10, 2025
    
    lim1 = mean - 10*std
    lim2 = mean + 10*std
    
    # Identify and log outliers before removing them
    outliers = wdf[(wdf[chem] > lim2) | (wdf[chem] < lim1)]
    for index, row in outliers.iterrows():
      outliers_removed.append({
          "River": riv,
          "Constituent": chem,
          "Date": index,
          "Value": row[chem],
          "Standard Deviations from Mean": (row[chem] - mean) / std
      })
    
    # Print the number of outliers found for debugging
    print(f"Outliers found for {riv} - {chem}: {len(outliers)}")
    
    # Remove outliers
    wdf = wdf[(wdf[chem] > lim1) & (wdf[chem] < lim2)]
    
    # Divide values by 1000 to convert from ug/L to mg/L
    wdf[chem] /= 1000
    
    #new TEMPORARY insert 2/5/2025 to trim conc data to available streamflow data date range
    flow_dates = flow_df.index  # Get available flow dates
    wdf = wdf[wdf["Date"].astype("str").isin(flow_dates)]  # Keep only concentration data for dates with flow
    #end insert
    assert flow_df[riv].notnull().all()
    
    # reorder the columns in wdf
    wdf = wdf[["Date", "remarks", chem]]

    # Because of rpy2 bugs or something idk, we need to convert the datetime to string first
    #wdf["Date"] = wdf["Date"].dt.strftime("%Y-%m-%d")
    
    return wdf

def save_outliers(path=default_out_data_path+"outliers_removed.csv"):
    outliers_df = pd.DataFrame(outliers_removed)
    outliers_df.to_csv(path, index=False)

# def verify():
#     # Verify the length of the trimmed streamflow data
#     for r, dailydf in daily_flow_dfs.items():
#         num_days = (dailydf.index.max() - dailydf.index.min()).days + 1  # Add 1 to include both start and end dates
#         print(f"River {r} has {num_days} days of data in the trimmed period.")
    
#     # Also verify if the number of leap years in the period
#     num_leap_years = len([year for year in range(start_date.year, end_date.year + 1) if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)])
#     print(f"Number of leap years in the period: {num_leap_years}")
    
#     # Check for any blank entries or NaNs in the flow files
#     for r, dailydf in daily_flow_dfs.items():
#         if dailydf.isnull().values.any():
#             print(f"Warning: River {r} has blank entries or NaNs in the flow data.")
#         else:
#             print(f"River {r} has no blank entries or NaNs in the flow data.")
